title: Marina Gardella
description: PhD candidate at Centre Borelli - ENS Paris-Saclay
site_title: '@marinagardella - Marina Gardella'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: marigardella
email: marigardella@gmail.com
twitter_username: GardellaMarina


# absolute or relative
profile_picture: assets/images/133308931_10164678695120581_1585104593470702110_o.jpg

# Google Analytics ID
google_analytics: 
