title: Marina Gardella
description: 
site_title: '@marigardella - Marina Gardella'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: marigardella
email: marigardella at" gmail "dot" com
twitter_username: GardellaMarina


# absolute or relative
profile_picture: assets/images/pp.jpg

# Google Analytics ID
google_analytics: 
